#!/bin/bash
chmod 440 $2

tmux \
	new -d -s $1 \; \
	split-window -h\; \
	split-window \; \
	select-pane -t 0\; \
	attach \; \
	send-keys './connect' Space $2 C-m\; \
	send-keys './intermediary' Space $2 C-m\; \

chmod 660 $2
